apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  creationTimestamp: null
  labels:
    component: networking
    provider: aws
    type: discovery
  name: network-discovery
spec:
  compositeTypeRef:
    apiVersion: xnetworks.crossplane.giantswarm.io/v1alpha1
    kind: Discovery
  mode: Pipeline
  pipeline:
  - functionRef:
      name: function-network-discovery
    input:
      apiVersion: xnetworks.crossplane.giantswarm.io/v1beta1
      kind: Input
      metadata:
        creationTimestamp: null
      spec:
        enabledRef: spec.enabled
        groupByRef: spec.groupBy
        patchTo: status.vpcs
        providerConfigRef: spec.providerConfigRef.name
        providerType: aws
        regionRef: spec.region
        vpcRef: spec.remoteVpcs
    step: network-discovery
  - functionRef:
      name: function-patch-and-transform
    input:
      apiVersion: pt.fn.crossplane.io/v1beta1
      kind: Resources
      metadata:
        creationTimestamp: null
      resources:
      - base:
          apiVersion: kubernetes.crossplane.io/v1alpha2
          kind: Object
          metadata:
            creationTimestamp: null
          spec:
            forProvider:
              manifest:
                apiVersion: v1
                kind: ConfigMap
                metadata:
                  name: ""
                  namespace: ""
                spec:
                  data: {}
            readiness: {}
          status:
            atProvider:
              manifest: null
        name: configmap
        patches:
        - fromFieldPath: spec.claimRef.name
          toFieldPath: metadata.name
          type: FromCompositeFieldPath
        - fromFieldPath: spec.kubernetesProviderConfigRef
          toFieldPath: spec.providerConfigRef
          type: FromCompositeFieldPath
        - fromFieldPath: spec.claimRef.namespace
          toFieldPath: spec.forProvider.manifest.metadata.namespace
          type: FromCompositeFieldPath
        - fromFieldPath: spec.claimRef.name
          toFieldPath: spec.forProvider.manifest.metadata.name
          transforms:
          - string:
              fmt: '%s-network-discovery'
              type: Format
            type: string
          type: FromCompositeFieldPath
        - fromFieldPath: status.vpcs
          toFieldPath: spec.forProvider.manifest.data.vpcs
          transforms:
          - string:
              convert: ToJson
              type: Convert
            type: string
          type: FromCompositeFieldPath
    step: function-patch-and-transform
