apiVersion: xnetworks.crossplane.giantswarm.io/v1alpha1
kind: DiscoveryClaim
metadata:
  labels:
    owner: honeybadger
    provider: aws
    app.kubernetes.io/name: discovery
    app.kubernetes.io/instance: discovery
    app.kubernetes.io/part-of: xnetworks
    app.kubernetes.io/managed-by: crossplane
  name: golem
  namespace: default
spec:
  deletionPolicy: Delete
  enabled: true
  groupBy: "giantswarm.io/subnetset"
  region: eu-west-2
  providerConfigRef:
    name: crossplane-network-discovery
  kubernetesProviderConfigRef:
    name: default
  providerType: aws
  remoteVpcs:
  - name: golem-vpc
  - name: operations-vpc
    region: eu-central-1
    providerConfigRef:
      name: aws-gazelle
