apiVersion: xnetworks.crossplane.giantswarm.io/v1alpha1
kind: DiscoveryClaim
metadata:
  labels:
    owner: honeybadger
    provider: aws
    app.kubernetes.io/name: discovery
    app.kubernetes.io/instance: discovery
    app.kubernetes.io/part-of: xnetworks
    app.kubernetes.io/managed-by: crossplane
  name: gazelle
  namespace: default
spec:
  deletionPolicy: Delete
  enabled: true
  groupBy: "giantswarm.io/subnetset"
  region: eu-west-2
  providerConfigRef:
    name: crossplane-network-discovery
  providerType: aws
  remoteVpcs:
  - name: gazelle-vpc
