---
apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: null
  name: eso
  namespace: org-presales-lutz
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: org-presales-lutz
  name: eso-store-role
rules:
- apiGroups: [""]
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - authorization.k8s.io
  resources:
  - selfsubjectrulesreviews
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: eso-store
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: eso-store-role
subjects:
- kind: ServiceAccount
  name: eso
  namespace: org-presales-lutz
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: default
  namespace: org-presales-lutz
spec:
  provider:
    kubernetes:
      remoteNamespace: org-presales-lutz
      server:
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt
      auth:
        serviceAccount:
          name: eso
