//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package eso

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Eso) DeepCopyInto(out *Eso) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.KubernetesSecretStore != nil {
		in, out := &in.KubernetesSecretStore, &out.KubernetesSecretStore
		*out = new(string)
		**out = **in
	}
	if in.Stores != nil {
		in, out := &in.Stores, &out.Stores
		*out = make([]*SecretsStore, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(SecretsStore)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Eso.
func (in *Eso) DeepCopy() *Eso {
	if in == nil {
		return nil
	}
	out := new(Eso)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Eso) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
