//go:build !ignore_autogenerated

/*
Copyright  The Crossbuilder Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/crossplane/crossplane-runtime/apis/common/v1"
	"github.com/giantswarm/crossplane-gs-apis/pkg/eso"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterDiscovery) DeepCopyInto(out *ClusterDiscovery) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterDiscovery.
func (in *ClusterDiscovery) DeepCopy() *ClusterDiscovery {
	if in == nil {
		return nil
	}
	out := new(ClusterDiscovery)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RCCWithRegionLookup) DeepCopyInto(out *RCCWithRegionLookup) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RCCWithRegionLookup.
func (in *RCCWithRegionLookup) DeepCopy() *RCCWithRegionLookup {
	if in == nil {
		return nil
	}
	out := new(RCCWithRegionLookup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RCCWithRegionLookup) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RCCWithRegionLookupList) DeepCopyInto(out *RCCWithRegionLookupList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RCCWithRegionLookup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RCCWithRegionLookupList.
func (in *RCCWithRegionLookupList) DeepCopy() *RCCWithRegionLookupList {
	if in == nil {
		return nil
	}
	out := new(RCCWithRegionLookupList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RCCWithRegionLookupList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RCCWithRegionLookupSpec) DeepCopyInto(out *RCCWithRegionLookupSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	out.ClusterDiscovery = in.ClusterDiscovery
	if in.KubernetesProviderConfig != nil {
		in, out := &in.KubernetesProviderConfig, &out.KubernetesProviderConfig
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	out.ManagementClusterDiscovery = in.ManagementClusterDiscovery
	in.RdsCacheClusterParameters.DeepCopyInto(&out.RdsCacheClusterParameters)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RCCWithRegionLookupSpec.
func (in *RCCWithRegionLookupSpec) DeepCopy() *RCCWithRegionLookupSpec {
	if in == nil {
		return nil
	}
	out := new(RCCWithRegionLookupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RCCWithRegionLookupStatus) DeepCopyInto(out *RCCWithRegionLookupStatus) {
	*out = *in
	in.ConditionedStatus.DeepCopyInto(&out.ConditionedStatus)
	if in.AvailabilityZones != nil {
		in, out := &in.AvailabilityZones, &out.AvailabilityZones
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.CacheClusterEndpoints != nil {
		in, out := &in.CacheClusterEndpoints, &out.CacheClusterEndpoints
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.CacheSubnets != nil {
		in, out := &in.CacheSubnets, &out.CacheSubnets
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.RdsSubnets != nil {
		in, out := &in.RdsSubnets, &out.RdsSubnets
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.Vpc.DeepCopyInto(&out.Vpc)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RCCWithRegionLookupStatus.
func (in *RCCWithRegionLookupStatus) DeepCopy() *RCCWithRegionLookupStatus {
	if in == nil {
		return nil
	}
	out := new(RCCWithRegionLookupStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RdsCacheCluster) DeepCopyInto(out *RdsCacheCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RdsCacheCluster.
func (in *RdsCacheCluster) DeepCopy() *RdsCacheCluster {
	if in == nil {
		return nil
	}
	out := new(RdsCacheCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RdsCacheCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RdsCacheClusterList) DeepCopyInto(out *RdsCacheClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RdsCacheCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RdsCacheClusterList.
func (in *RdsCacheClusterList) DeepCopy() *RdsCacheClusterList {
	if in == nil {
		return nil
	}
	out := new(RdsCacheClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RdsCacheClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RdsCacheClusterParameters) DeepCopyInto(out *RdsCacheClusterParameters) {
	*out = *in
	in.Cache.DeepCopyInto(&out.Cache)
	in.Database.DeepCopyInto(&out.Database)
	if in.Eso != nil {
		in, out := &in.Eso, &out.Eso
		*out = new(eso.Eso)
		(*in).DeepCopyInto(*out)
	}
	out.SubnetGroupIndexes = in.SubnetGroupIndexes
	in.Vpc.DeepCopyInto(&out.Vpc)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RdsCacheClusterParameters.
func (in *RdsCacheClusterParameters) DeepCopy() *RdsCacheClusterParameters {
	if in == nil {
		return nil
	}
	out := new(RdsCacheClusterParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RdsCacheClusterSpec) DeepCopyInto(out *RdsCacheClusterSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	if in.AvailabilityZones != nil {
		in, out := &in.AvailabilityZones, &out.AvailabilityZones
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.KubernetesProviderConfig != nil {
		in, out := &in.KubernetesProviderConfig, &out.KubernetesProviderConfig
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	in.RdsCacheClusterParameters.DeepCopyInto(&out.RdsCacheClusterParameters)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RdsCacheClusterSpec.
func (in *RdsCacheClusterSpec) DeepCopy() *RdsCacheClusterSpec {
	if in == nil {
		return nil
	}
	out := new(RdsCacheClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RdsClusterStatus) DeepCopyInto(out *RdsClusterStatus) {
	*out = *in
	in.ConditionedStatus.DeepCopyInto(&out.ConditionedStatus)
	if in.CacheClusterEndpoints != nil {
		in, out := &in.CacheClusterEndpoints, &out.CacheClusterEndpoints
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.CacheSubnets != nil {
		in, out := &in.CacheSubnets, &out.CacheSubnets
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.RdsSubnets != nil {
		in, out := &in.RdsSubnets, &out.RdsSubnets
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.Vpc.DeepCopyInto(&out.Vpc)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RdsClusterStatus.
func (in *RdsClusterStatus) DeepCopy() *RdsClusterStatus {
	if in == nil {
		return nil
	}
	out := new(RdsClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubnetGroupIndexes) DeepCopyInto(out *SubnetGroupIndexes) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubnetGroupIndexes.
func (in *SubnetGroupIndexes) DeepCopy() *SubnetGroupIndexes {
	if in == nil {
		return nil
	}
	out := new(SubnetGroupIndexes)
	in.DeepCopyInto(out)
	return out
}
