---
apiVersion: xcache.crossplane.giantswarm.io/v1alpha1
kind: ElasticacheClaim
metadata:
  name: xcache-redis-replication
  namespace: default
  labels:
    owner: honeybadger
    provider: aws
    app.kubernetes.io/name: myapp
    app.kubernetes.io/instance: myapp-elasticache-redis-replication
    app.kubernetes.io/part-of: myapp
    app.kubernetes.io/managed-by: crossplane
spec:
  compositionSelector:
    matchLabels:
      provider: aws
      component: elasticache
      type: base

  providerConfigRef:
    name: default

  availabilityZones: ["a", "b", "c"]
  region: eu-central-1

  createReplicationGroup: true
  engine: redis
  engineVersion: "7.1"
  nodeType: cache.t3.micro
  numCacheClusters: 3
  tags:
    giantswarm.io/owner: honeybadger
    giantswarm.io/managed-by: crossplane
    giantswarm.io/part-of: myapp

  vpcId: vpc-d2772f2e
  subnetIds:
  - subnet-b5e6dd7a
  - subnet-61e810d1
  - subnet-0b5872a3
