apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  creationTimestamp: null
  labels:
    component: database
    provider: aws
    type: base
  name: rds-cache-cluster
spec:
  compositeTypeRef:
    apiVersion: xdatabase.crossplane.giantswarm.io/v1alpha1
    kind: RdsCacheCluster
  mode: Pipeline
  pipeline:
  - functionRef:
      name: function-patch-and-transform
    input:
      metadata:
        creationTimestamp: null
      resources:
      - base:
          apiVersion: xnetworks.crossplane.giantswarm.io/v1alpha1
          kind: PeeredVpcNetwork
          metadata:
            creationTimestamp: null
          spec:
            peering:
              allowPublic: false
              enabled: false
              remoteVpcs: null
            region: ""
            subnetsets:
              availabilityZones: null
              cidrs: null
              function: ""
            tags: {}
          status:
            calculatedCidrs: null
            subnetBits: null
        name: peered-vpc-network
        patches:
        - fromFieldPath: spec.vpc
          toFieldPath: spec
          type: FromCompositeFieldPath
        - fromFieldPath: spec.region
          toFieldPath: spec.region
          type: FromCompositeFieldPath
        - fromFieldPath: status.atProvider.vpcId
          toFieldPath: status.vpcId
          type: ToCompositeFieldPath
      - base:
          apiVersion: xdatabases.crossplane.giantswarm.io/v1alpha1
          kind: RdsBaseClaim
          metadata:
            creationTimestamp: null
          spec:
            cidrBlocks: null
            dbClusterParameterGroup: null
            region: null
            subnetIds: null
            vpcId: null
          status: {}
        name: rds-base
        patches:
        - fromFieldPath: spec.database
          toFieldPath: spec
          type: FromCompositeFieldPath
        - fromFieldPath: spec.region
          toFieldPath: spec.region
          type: FromCompositeFieldPath
    step: patch-and-transform
  - functionRef:
      name: function-kcl
    input:
      apiVersion: krm.kcl.dev/v1alpha1
      kind: KCLInput
      metadata:
        creationTimestamp: null
      spec:
        config: {}
        credentials:
          password: ""
          username: ""
        source: |-
          import regex

          _oxr = option("params").oxr
          _dxr = option("params").dxr
          _ocds = option("params").ocds
          _dcds = option("params").dcds

          get = lambda x: any, y: str, d: any -> any {
              """
              Get an item from a dictionary using a dot separated path.
              If the item is not found, return a default value.
              """
              p = regex.split(y, "\.")
              c = p[0]
              y = ".".join(p[1:])
              x[c] if len(p) == 1 and c in x else d if c not in x else get(x[c], y, d)
          }

          _subnets = get(_ocds, "peered-vpc-network.Resource.status.privateSubnets", [])

          _dbsnindex = get(_oxr, "spec.subnetGroupIndex.database", False)
          _dbSnIds = [k for _, k in _subnets[_dbsnindex]] if _dbsnindex and _subnets else []

          _cachesnindex = get(_oxr, "spec.subnetGroupIndex.cache", False)
          _cacheSnIds = [k for _, k in _subnets[_cachesnindex]] if _cachesnindex and _subnets else []

          _dbPatch = {
              **get(_dcds, "rds-cluster.Resource", {}),
              **{
                  "metadata": {
                      annotations: {
                          "krm.kcl.dev/composition-resource-name" = "rds-cluster"
                      }
                  }
                  "spec": {
                      "subnetIds": _dbSnIds
                      "vpcId": get(_oxr, "status.vpcId", "")
                  }
              }
          } if all_true([
              _dbSnIds,
              get(_dcds, "rds-cluster.Resource", False),
              get(_oxr, "status.vpcId", False),
          ]) else {}

          _cachePatch = {
              **get(_dcds, "cache-cluster.Resource", {}),
              **{
                  "metadata": {
                      annotations: {
                          "krm.kcl.dev/composition-resource-name" = "cache-cluster"
                      }
                  }
                  "spec": {
                      "subnetIds": _cacheSnIds
                      "vpcId": get(_oxr, "status.vpcId", "")
                  }
              }
          } if all_true([
              _cacheSnIds,
              get(_oxr, "spec.cache", False),
              get(_oxr, "status.vpcId", False),
          ]) else {}

          items = [
              k for _, k in [_dbPatch, _cachePatch] if k
          ]
        target: ""
    step: function-kcl-dynamic-patch
