apiVersion: xdatabase.crossplane.giantswarm.io/v1alpha1
kind: LogicalDatabaseClaim
metadata:
  name: test-logical-database
  namespace: org-demotech
spec:
  eso:
    enabled: true
    fluxSSASecretName: fluxssa
    kubernetesSecretStore: default
  engine: aurora-mysql
  kubernetesProviderConfig:
    name: default
  providerConfigRef:
    name: cloudtest-aurora-mysql-tgw-mysql-provider-config
