---
apiVersion: xdatabase.crossplane.giantswarm.io/v1alpha1
kind: RdsBaseClaim
metadata:
  name: myapp-multiaz-rds
  namespace: default
  labels:
    owner: honeybadger
    provider: aws
    app.kubernetes.io/name: myapp
    app.kubernetes.io/instance: myapp-database
    app.kubernetes.io/part-of: myapp
    app.kubernetes.io/managed-by: crossplane
spec:
  availabilityZones: ["a", "b", "c"]
  allocatedStorage: 20

  cidrBlocks:
  - 10.8.0.0/24

  createCluster: false

  compositionSelector:
    matchLabels:
      provider: aws
      component: database
      type: base

  deletionPolicy: Delete

  enabledCloudwatchLogsExports: ["postgresql"]

  cloudwatchLogGroupParameters:
    retentionInDays: 7
    class: standard
    create: false

  engine: postgres
  engineVersion: "14.5"

  dbClusterInstanceClass: db.t3.medium

  iops: 1000

  instances:
    - {}

  masterUsername: admin
  providerConfigRef:
    name: default

  region: eu-central-1
  multiAz: true

  secretRotation:
    enabled: false
    automaticallyAfterDays: 30
    rotateImmediately: true

  storageType: io1

  subnetIds:
  - subnet-345ec307
  - subnet-05efd075
  - subnet-4ce4fbde


  vpcId: vpc-c32dcdc9
