---
apiVersion: xdatabase.crossplane.giantswarm.io/v1alpha1
kind: MultiAzClusterClaim
metadata:
  name: myapp-multiaz-rds-autoscaling
  namespace: default
  labels:
    owner: honeybadger
    provider: aws
    app.kubernetes.io/name: myapp
    app.kubernetes.io/instance: myapp-database
    app.kubernetes.io/part-of: myapp
    app.kubernetes.io/managed-by: crossplane
spec:
  availabilityZones: ["a", "b", "c"]
  allocatedStorage: 20

  autoscaling:
    enabled: true
    minCapacity: 3
    maxCapacity: 5

  cidrBlocks:
  - 10.8.0.0/24
  compositionSelector:
    matchLabels:
      provider: aws
      component: cluster

  deletionPolicy: Delete

  enabledCloudwatchLogsExports: ["postgresql"]

  cloudwatchLogGroupParameters:
    retentionInDays: 7
    class: standard
    create: false

  engine: aurora-postgresql
  engineVersion: "14.5"

  dbClusterInstanceClass: db.t3.medium

  instances:
    - {}
    - {}

  iops: 1000

  masterUsername: admin
  providerConfigRef:
    name: default

  region: eu-central-1
  multiAZ: true

  secretRotation:
    enabled: false
    automaticallyAfterDays: 30
    rotateImmediately: true

  storageType: io1

  subnetIds:
  - subnet-237e86eb
  - subnet-d09d9704
  - subnet-f169918d

  vpcId: vpc-2c5a85cf
