---
apiVersion: xdatabase.crossplane.giantswarm.io/v1alpha1
kind: RdsCacheClusterClaim
metadata:
  name: cloudtest-rds-elasticache
  namespace: default
  labels:
    owner: honeybadger
    provider: aws
    app.kubernetes.io/name: myapp
    app.kubernetes.io/instance: myapp-elasticache-database
    app.kubernetes.io/part-of: myapp
    app.kubernetes.io/managed-by: crossplane
spec:
  availabilityZones: ["a", "b", "c"]
  compositionSelector:
    matchLabels:
      provider: aws
      component: database
      type: rds-cluster

  subnetGroupIndexes:
    cache: 0
    database: 1

  database:
    allocatedStorage: 100
    createCluster: false
    enabledCloudwatchLogsExports: ["postgresql"]
    cloudwatchLogGroupParameters:
      retentionInDays: 7
      class: standard
      create: false
    engine: postgres
    engineVersion: "15.6"
    dbClusterInstanceClass: db.t3.medium
    iops: 1000
    instanceCount: 3
    masterUsername: giantswarm
    multiAz: true
    secretRotation:
      enabled: false
    storageType: io1

  deletionPolicy: Delete
  providerConfigRef:
    name: aws-golem
  region: eu-central-1

  vpc:
    peering:
      remoteVpcs:
      - name: golem-vpc
        region: eu-west-2
        allowPublic: true
      enabled: true
    subnetsets:
      cidrs:
      - prefix: '10.16.0.0/24'
        public:
          mask: ""
          count: 0
          lbSetIndex: -1
        private:
          mask: /28
          count: 2
          lbSetIndex: -1
    tags:
      common:
        giantswarm.io/owner: honeybadger
        giantswarm.io/managed-by: crossplane
        giantswarm.io/part-of: myapp