---
apiVersion: xcomposite.crossplane.giantswarm.io/v1alpha1
kind: RCCWithRegionLookupClaim
metadata:
  name: cloudtest-aurora-mysql-tgw
  namespace: default
  labels:
    owner: honeybadger
    provider: aws
    app.kubernetes.io/name: myapp
    app.kubernetes.io/instance: myapp-elasticache-aurora-cluster
    app.kubernetes.io/part-of: myapp
    app.kubernetes.io/managed-by: crossplane
spec:

  deletionPolicy: Delete

  providerConfigRef:
    name: aws-golem

  kubernetesProviderConfig:
    name: default

  clusterDiscovery:
    name: "rdsapp"
    namespace: "org-demotech"

  managementClusterDiscovery:
    name: "golem"
    namespace: "org-giantswarm"

  rdsCacheClusterParameters:
    eso:
      enabled: true
      kubernetesSecretStore: default
      fluxSSASecretName: fluxssa

    cache:
      createReplicationGroup: true
      engine: redis
      engineVersion: "7.1"
      nodeType: cache.t3.micro
      numCacheClusters: 3
      transitEncryptionEnabled: true

    database:
      createCluster: true
      enabledCloudwatchLogsExports:
        - audit
        - error
        - general
        - slowquery
      autoscaling:
        enabled: false
      cloudwatchLogGroupParameters:
        retentionInDays: 7
        class: standard
        create: false
      engine: aurora-mysql
      engineVersion: "8.0.mysql_aurora.3.06.0"
      instanceCount: 3
      masterUsername: giantswarm
      storageType: aurora

    subnetGroupIndexes:
      cache: 0
      database: 1

    vpc:
      peering:
        enabled: true
        remoteVpcs:
        - name: rdsapp-vpc
          region: eu-west-2
          allowPublic: true
      transitGateway:
        enabled: true
        remoteVpcs:
        - name: golem-vpc
          region: eu-west-2
          allowPublic: true
      subnetsets:
        cidrs:
        - prefix: '10.18.0.0/24'
          public:
            mask: ""
            count: 0
          private:
            mask: /28
            count: 2
      tags:
        common:
          giantswarm.io/owner: honeybadger
          giantswarm.io/managed-by: crossplane
          giantswarm.io/part-of: myapp
