//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterDiscovery) DeepCopyInto(out *ClusterDiscovery) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterDiscovery.
func (in *ClusterDiscovery) DeepCopy() *ClusterDiscovery {
	if in == nil {
		return nil
	}
	out := new(ClusterDiscovery)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RdsCacheClusterWithRegionLookup) DeepCopyInto(out *RdsCacheClusterWithRegionLookup) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RdsCacheClusterWithRegionLookup.
func (in *RdsCacheClusterWithRegionLookup) DeepCopy() *RdsCacheClusterWithRegionLookup {
	if in == nil {
		return nil
	}
	out := new(RdsCacheClusterWithRegionLookup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RdsCacheClusterWithRegionLookup) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RdsCacheClusterWithRegionLookupList) DeepCopyInto(out *RdsCacheClusterWithRegionLookupList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RdsCacheClusterWithRegionLookup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RdsCacheClusterWithRegionLookupList.
func (in *RdsCacheClusterWithRegionLookupList) DeepCopy() *RdsCacheClusterWithRegionLookupList {
	if in == nil {
		return nil
	}
	out := new(RdsCacheClusterWithRegionLookupList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RdsCacheClusterWithRegionLookupList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RdsCacheClusterWithRegionLookupSpec) DeepCopyInto(out *RdsCacheClusterWithRegionLookupSpec) {
	*out = *in
	in.ClusterDiscovery.DeepCopyInto(&out.ClusterDiscovery)
	in.RdsCacheClusterSpec.DeepCopyInto(&out.RdsCacheClusterSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RdsCacheClusterWithRegionLookupSpec.
func (in *RdsCacheClusterWithRegionLookupSpec) DeepCopy() *RdsCacheClusterWithRegionLookupSpec {
	if in == nil {
		return nil
	}
	out := new(RdsCacheClusterWithRegionLookupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RdsCacheClusterWithRegionLookupStatus) DeepCopyInto(out *RdsCacheClusterWithRegionLookupStatus) {
	*out = *in
	in.ConditionedStatus.DeepCopyInto(&out.ConditionedStatus)
	if in.CacheClusterEndpoints != nil {
		in, out := &in.CacheClusterEndpoints, &out.CacheClusterEndpoints
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.CacheSubnets != nil {
		in, out := &in.CacheSubnets, &out.CacheSubnets
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.RdsSubnets != nil {
		in, out := &in.RdsSubnets, &out.RdsSubnets
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.Vpc.DeepCopyInto(&out.Vpc)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RdsCacheClusterWithRegionLookupStatus.
func (in *RdsCacheClusterWithRegionLookupStatus) DeepCopy() *RdsCacheClusterWithRegionLookupStatus {
	if in == nil {
		return nil
	}
	out := new(RdsCacheClusterWithRegionLookupStatus)
	in.DeepCopyInto(out)
	return out
}
