apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  creationTimestamp: null
  labels:
    component: database
    provider: aws
    type: base
  name: rds-cache-cluster
spec:
  compositeTypeRef:
    apiVersion: xcomposite.crossplane.giantswarm.io/v1alpha1
    kind: RdsCacheCluster
  mode: Pipeline
  pipeline:
  - functionRef:
      name: function-patch-and-transform
    input:
      apiVersion: pt.crossplane.io/v1beta1
      kind: Resources
      metadata:
        creationTimestamp: null
      patchSets:
      - name: metadata
        patches:
        - fromFieldPath: metadata.labels
          policy:
            toFieldPath: MergeObjects
          toFieldPath: metadata.labels
          type: FromCompositeFieldPath
        - fromFieldPath: spec.region
          toFieldPath: metadata.labels.region
          type: FromCompositeFieldPath
        - fromFieldPath: spec.providerConfigRef
          toFieldPath: spec.providerConfigRef
          type: FromCompositeFieldPath
        - fromFieldPath: spec.deletionPolicy
          toFieldPath: spec.deletionPolicy
          type: FromCompositeFieldPath
      - name: commontags
        patches:
        - fromFieldPath: spec.tags
          policy:
            toFieldPath: MergeObjects
          toFieldPath: spec.forProvider.tags
          type: FromCompositeFieldPath
        - fromFieldPath: metadata.labels
          policy:
            toFieldPath: MergeObjects
          toFieldPath: spec.forProvider.tags
          type: FromCompositeFieldPath
        - fromFieldPath: spec.region
          toFieldPath: spec.forProvider.tags.region
          type: FromCompositeFieldPath
      resources:
      - base:
          apiVersion: xnetworks.crossplane.giantswarm.io/v1alpha1
          kind: PeeredVpcNetwork
          metadata:
            creationTimestamp: null
          spec:
            availabilityZones: null
            peering:
              allowPublic: false
              enabled: false
              groupBy: ""
              remoteVpcs: null
            region: ""
            subnetsets:
              cidrs: null
              function: ""
            tags: {}
            transitGateway:
              allowPublic: false
              cidrBlocks: null
              enabled: false
              peers: null
              prefixList: null
              prefixLists: null
              ram:
                allowExternalPrincipals: false
                enabled: false
                principals: null
              region: ""
              remoteVpcs: null
              routeTableIds: null
              subnetIds: null
              vpcId: ""
          status:
            calculatedCidrs: null
            subnetBits: null
            vpcLookup:
              enabled: false
              groupBy: ""
              remoteVpcs: null
        name: peered-vpc-network
        patches:
        - fromFieldPath: spec.vpc
          toFieldPath: spec
          type: FromCompositeFieldPath
        - fromFieldPath: spec.availabilityZones
          toFieldPath: spec.availabilityZones
          type: FromCompositeFieldPath
        - fromFieldPath: spec.claimRef
          toFieldPath: spec.claimRef
          type: FromCompositeFieldPath
        - fromFieldPath: spec.deletionPolicy
          toFieldPath: spec.deletionPolicy
          type: FromCompositeFieldPath
        - fromFieldPath: spec.managementPolicies
          toFieldPath: spec.managementPolicies
          type: FromCompositeFieldPath
        - fromFieldPath: spec.region
          toFieldPath: spec.region
          type: FromCompositeFieldPath
        - fromFieldPath: spec.providerConfigRef
          toFieldPath: spec.providerConfigRef
          type: FromCompositeFieldPath
        - fromFieldPath: status.vpcs.self
          toFieldPath: status.vpc
          type: ToCompositeFieldPath
      - base:
          apiVersion: xcache.crossplane.giantswarm.io/v1alpha1
          kind: CacheBase
          metadata:
            creationTimestamp: null
          spec:
            engine: null
            parameterGroupConfiguration:
              family: null
              name: null
            region: null
            vpcId: null
          status: {}
        name: cache-base
        patches:
        - fromFieldPath: spec.cache
          toFieldPath: spec
          type: FromCompositeFieldPath
        - fromFieldPath: spec.availabilityZones
          toFieldPath: spec.availabilityZones
          type: FromCompositeFieldPath
        - fromFieldPath: spec.claimRef
          toFieldPath: spec.claimRef
          type: FromCompositeFieldPath
        - fromFieldPath: spec.deletionPolicy
          toFieldPath: spec.deletionPolicy
          type: FromCompositeFieldPath
        - fromFieldPath: spec.eso
          toFieldPath: spec.eso
          type: FromCompositeFieldPath
        - fromFieldPath: spec.kubernetesProviderConfig
          toFieldPath: spec.kubernetesProviderConfig
          type: FromCompositeFieldPath
        - fromFieldPath: spec.managementPolicies
          toFieldPath: spec.managementPolicies
          type: FromCompositeFieldPath
        - fromFieldPath: spec.providerConfigRef
          toFieldPath: spec.providerConfigRef
          type: FromCompositeFieldPath
        - fromFieldPath: spec.region
          toFieldPath: spec.region
          type: FromCompositeFieldPath
        - fromFieldPath: status.vpc.id
          policy:
            fromFieldPath: Required
          toFieldPath: spec.vpcId
          type: FromCompositeFieldPath
        - fromFieldPath: status.connectionSecret
          toFieldPath: status.cacheConnectionSecret
          type: ToCompositeFieldPath
        - fromFieldPath: status.clusterEndpoints
          toFieldPath: status.cacheClusterEndpoints
          type: ToCompositeFieldPath
        - fromFieldPath: status.endpoint
          toFieldPath: status.cacheEndpoint
          type: ToCompositeFieldPath
        - fromFieldPath: status.readerEndpoint
          toFieldPath: status.cacheReaderEndpoint
          type: ToCompositeFieldPath
        - fromFieldPath: status.globalConnectionSecret
          toFieldPath: status.cacheGlobalConnectionSecret
          type: ToCompositeFieldPath
        - fromFieldPath: status.globalEndpoint
          toFieldPath: status.cacheGlobalEndpoint
          type: ToCompositeFieldPath
        - fromFieldPath: status.globalReaderEndpoint
          toFieldPath: status.cacheGlobalReaderEndpoint
          type: ToCompositeFieldPath
        - fromFieldPath: status.port
          toFieldPath: status.cachePort
          type: ToCompositeFieldPath
      - base:
          apiVersion: xdatabase.crossplane.giantswarm.io/v1alpha1
          kind: RdsBase
          metadata:
            creationTimestamp: null
          spec:
            cidrBlocks: null
            dbClusterParameterGroup: null
            region: null
            subnetIds: null
            vpcId: null
          status: {}
        name: rds-base
        patches:
        - fromFieldPath: spec.database
          toFieldPath: spec
          type: FromCompositeFieldPath
        - fromFieldPath: spec.availabilityZones
          toFieldPath: spec.availabilityZones
          type: FromCompositeFieldPath
        - fromFieldPath: spec.claimRef
          toFieldPath: spec.claimRef
          type: FromCompositeFieldPath
        - fromFieldPath: spec.deletionPolicy
          toFieldPath: spec.deletionPolicy
          type: FromCompositeFieldPath
        - fromFieldPath: spec.eso
          toFieldPath: spec.eso
          type: FromCompositeFieldPath
        - fromFieldPath: spec.kubernetesProviderConfig
          toFieldPath: spec.kubernetesProviderConfig
          type: FromCompositeFieldPath
        - fromFieldPath: spec.managementPolicies
          toFieldPath: spec.managementPolicies
          type: FromCompositeFieldPath
        - fromFieldPath: spec.providerConfigRef
          toFieldPath: spec.providerConfigRef
          type: FromCompositeFieldPath
        - fromFieldPath: spec.region
          toFieldPath: spec.region
          type: FromCompositeFieldPath
        - fromFieldPath: status.vpc.id
          policy:
            fromFieldPath: Required
          toFieldPath: spec.vpcId
          type: FromCompositeFieldPath
        - fromFieldPath: status.connectionSecret
          toFieldPath: status.rdsConnectionSecret
          type: ToCompositeFieldPath
        - fromFieldPath: status.endpoint
          toFieldPath: status.rdsEndpoint
          type: ToCompositeFieldPath
        - fromFieldPath: status.port
          toFieldPath: status.rdsPort
          type: ToCompositeFieldPath
    step: patch-and-transform
  - functionRef:
      name: function-kcl
    input:
      apiVersion: krm.kcl.dev/v1alpha1
      kind: KCLInput
      metadata:
        creationTimestamp: null
      spec:
        source: |-
          import regex

          _oxr = option("params").oxr
          _dxr = option("params").dxr
          _ocds = option("params").ocds
          _dcds = option("params").dcds

          get = lambda x: {:}, y: str, d: any -> any {
              """
              Get an item from a dictionary using a dot separated path.
              If the item is not found, return a default value.
              """
              p = regex.split(y, "\.")
              c = p[0]
              y = ".".join(p[1:])
              x[c] if len(p) == 1 and c in x else d if c not in x else get(x[c], y, d)
          }

          ocdsstatus = lambda x: str, y: str, d: any -> any {
              """
              Get an item from the status of an ocds resource.
              """
              _x = None
              if get(_ocds, "${x}.Resource.status.atProvider", False):
                  get(_ocds, "${x}.Resource.status.atProvider.${y}", d)
              else:
                  _x = get(_ocds, "${x}.Resource.status.${y}", d)
              _x if _x else d
          }

          exists = lambda x: any -> bool {
              """
              Check if a value exists.
              """
              x in list(_ocds)
          }

          ready = lambda x: str -> bool {
              """
              Check if a value is ready.
              """
              conditions = get(_ocds, "${x}.Resource.status.conditions", [])
              any_true([
                  all_true([
                      get(c, "status", "False") == "True" for c in conditions
                  ])
              ])
          }

          readystr = lambda x: str -> str {
              """
              Check if a value is ready.
              """
              "True" if ready(x) else "False"
          }


          # AppName here must be all lowercase with all symbols removed
          appName = regex.replace(get(_oxr, "spec.claimRef.name", ""), "[-_\.]", "_").lower()
          dp = get(_oxr, "spec.deletionPolicy", "Delete")
          mgmtPolicy = get(_oxr, "spec.managementPolicies", [])
          namespace = get(_oxr, "spec.claimRef.namespace", "default")
          pcr = get(_oxr, "spec.providerConfigRef", {"name": "default"})

          ssasecret = get(_oxr, "spec.eso.fluxSSASecret", "")
          # The resource created here is to enable switching Flux SSA from `Ignore` to
          # `Merge`.
          #
          # This allows Flux to ignore the creation of resources until the related
          # infrastructure has been created and is ready.
          #
          # To enable this, Any resources created by Flux kustomization should have the
          # annotation `kustomize.toolkit.fluxcd.io/ssa: ${PROJECT_NAME_SSA:=Ignore}`.
          #
          # This will then force SSA to `Ingore` the resource by default.
          #
          # Next, the flux kusomization should have its `postBuild` set up like follows:
          #
          # ```yaml
          # postBuild:
          #   substitute:
          #     var_substitution_enabled: "true"
          #   substituteFrom:
          #   - kind: Secret
          #     name: flux-project-ssa
          # ```
          _items = [
              {
                  "apiVersion": "kubernetes.crossplane.io/v1alpha2"
                  "kind": "Object"
                  "metadata": {
                      "annotations": {
                          "krm.kcl.dev/composition-resource-name" = "${appName}-externalsecret"
                          "krm.kcl.dev/ready": readystr("${appName}-externalsecret")
                      }
                  }
                  "spec": {
                      "deletionPolicy": dp,
                      "forProvider": {
                          "manifest": {
                              "apiVersion": "external-secrets.io/v1beta1",
                              "kind": "ExternalSecret",
                              "metadata": {
                                  "namespace": namespace,
                              },
                              "spec": {
                                  "refreshInterval": "1d",
                                  "secretStoreRef": {
                                      "name": get(_oxr, "spec.eso.secretStoreRef.name", ""),
                                      "kind": "SecretStore",
                                  },
                                  "dataFrom": [
                                      {
                                          "find": {
                                              "name": {
                                                  "regexp": "^${ssasecret}$",
                                              },
                                          },
                                      },
                                  ],
                                  "target": {
                                      "name": ssasecret,
                                      "creationPolicy": "Orphan",
                                      "template": {
                                          "engineVersion": "v2",
                                          "mergePolicy": "Merge",
                                          "data": {
                                              "${ssasecret}": "",
                                              "${appName}" = '{{ "Merge" | b64enc }}',
                                          },
                                      }
                                  }
                              }
                          }
                      }
                      "managementPolicies": mgmtPolicy,
                      "providerConfigRef": {
                          "name": get(_oxr, "spec.kubernetesProviderConfig.name", "")
                      }
                  }
              }
              for _ in [True]
              if all_true([
                  get(_oxr, "spec.eso.enabled", False),
                  get(_oxr, "spec.eso.fluxSSASecret", False),
                  get(_oxr, "status.cacheConnectionSecret", False),
                  get(_oxr, "status.rdsConnectionSecret", False),
              ])
          ]

          items = _items
        target: ""
    step: function-kcl-create-eso-secret
  - functionRef:
      name: function-kcl
    input:
      apiVersion: krm.kcl.dev/v1alpha1
      kind: KCLInput
      metadata:
        creationTimestamp: null
      spec:
        source: |-
          import regex

          _oxr = option("params").oxr
          _dxr = option("params").dxr
          _ocds = option("params").ocds
          _dcds = option("params").dcds

          get = lambda x: {:}, y: str, d: any -> any {
              """
              Get an item from a dictionary using a dot separated path.
              If the item is not found, return a default value.
              """
              p = regex.split(y, "\.")
              c = p[0]
              y = ".".join(p[1:])
              x[c] if len(p) == 1 and c in x else d if c not in x else get(x[c], y, d)
          }

          ocdsstatus = lambda x: str, y: str, d: any -> any {
              """
              Get an item from the status of an ocds resource.
              """
              _x = None
              if get(_ocds, "${x}.Resource.status.atProvider", False):
                  get(_ocds, "${x}.Resource.status.atProvider.${y}", d)
              else:
                  _x = get(_ocds, "${x}.Resource.status.${y}", d)
              _x if _x else d
          }

          exists = lambda x: any -> bool {
              """
              Check if a value exists.
              """
              x in list(_ocds)
          }

          ready = lambda x: str -> bool {
              """
              Check if a value is ready.
              """
              conditions = get(_ocds, "${x}.Resource.status.conditions", [])
              any_true([
                  all_true([
                      get(c, "status", "False") == "True" for c in conditions
                  ])
              ])
          }

          readystr = lambda x: str -> str {
              """
              Check if a value is ready.
              """
              "True" if ready(x) else "False"
          }


          # AppName here must be all lowercase with all symbols removed
          appName = regex.replace(get(_oxr, "spec.claimRef.name", ""), "[-_\.]", "_").lower()
          dp = get(_oxr, "spec.deletionPolicy", "Delete")
          mgmtPolicy = get(_oxr, "spec.managementPolicies", [])
          namespace = get(_oxr, "spec.claimRef.namespace", "default")
          pcr = get(_oxr, "spec.providerConfigRef", {"name": "default"})

          _subnets = get(_oxr, "status.vpc.privateSubnets", [])

          _dbsnindex = get(_oxr, "spec.subnetGroupIndexes.database", False)
          _dbSnIds = [k.id for _, k in _subnets[_dbsnindex]] if _dbsnindex != False and _subnets else []

          _cachesnindex = get(_oxr, "spec.subnetGroupIndexes.cache", False)
          _cacheSnIds = [k.id for _, k in _subnets[_cachesnindex]] if _cachesnindex != False and _subnets else []


          vpcs = ocdsstatus("peered-vpc-network", "vpcs", {})

          cidrBlocks = [
              i for r in [
                  [ get(vpc, "cidrBlock", "") ] + get(vpc, "additionalCidrBlocks", [])
                  for _, vpc in vpcs
              ]
              for i in r if i
          ]

          _dbPatch = {
              **get(_dcds, "rds-base.Resource", {}),
              **{
                  "metadata": {
                      "annotations": {
                          "krm.kcl.dev/composition-resource-name" = "rds-base"
                      }
                  }
                  "spec": {
                      "cidrBlocks": cidrBlocks,
                      "subnetIds": _dbSnIds
                  }
              }
          } if all_true([
              _dbSnIds,
              get(_dcds, "rds-base.Resource", False),
              get(_oxr, "status.vpc.id", False),
          ]) else {}

          _cachePatch = {
              **get(_dcds, "cache-base.Resource", {}),
              **{
                  "metadata": {
                      "annotations": {
                          "krm.kcl.dev/composition-resource-name" = "cache-base"
                      }
                  }
                  "spec": {
                      "cidrBlocks": cidrBlocks,
                      "subnetIds": _cacheSnIds
                  }
              }
          } if all_true([
              _cacheSnIds,
              get(_dcds, "cache-base.Resource", False),
              get(_oxr, "spec.cache", False),
              get(_oxr, "status.vpc.id", False),
          ]) else {}

          items = [
              k for _, k in [_dbPatch, _cachePatch] if k
          ]
        target: ""
    step: function-kcl-dynamic-patch
  - functionRef:
      name: function-auto-ready
    step: function-auto-ready
