//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/crossplane/crossplane-runtime/apis/common/v1"
	"github.com/giantswarm/crossplane-fn-network-discovery/pkg/composite/v1beta1"
	inputv1beta1 "github.com/mproffitt/function-cidr/input/v1beta1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Discovery) DeepCopyInto(out *Discovery) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Discovery.
func (in *Discovery) DeepCopy() *Discovery {
	if in == nil {
		return nil
	}
	out := new(Discovery)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Discovery) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiscoveryList) DeepCopyInto(out *DiscoveryList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Discovery, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiscoveryList.
func (in *DiscoveryList) DeepCopy() *DiscoveryList {
	if in == nil {
		return nil
	}
	out := new(DiscoveryList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DiscoveryList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiscoverySpec) DeepCopyInto(out *DiscoverySpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.KubernetesProviderConfigRef.DeepCopyInto(&out.KubernetesProviderConfigRef)
	if in.RemoteVpcs != nil {
		in, out := &in.RemoteVpcs, &out.RemoteVpcs
		*out = make([]VpcPeer, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiscoverySpec.
func (in *DiscoverySpec) DeepCopy() *DiscoverySpec {
	if in == nil {
		return nil
	}
	out := new(DiscoverySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiscoveryStatus) DeepCopyInto(out *DiscoveryStatus) {
	*out = *in
	in.ConditionedStatus.DeepCopyInto(&out.ConditionedStatus)
	if in.Vpcs != nil {
		in, out := &in.Vpcs, &out.Vpcs
		*out = make(map[string]v1beta1.AwsVpc, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiscoveryStatus.
func (in *DiscoveryStatus) DeepCopy() *DiscoveryStatus {
	if in == nil {
		return nil
	}
	out := new(DiscoveryStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedPrefixList) DeepCopyInto(out *ManagedPrefixList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedPrefixList.
func (in *ManagedPrefixList) DeepCopy() *ManagedPrefixList {
	if in == nil {
		return nil
	}
	out := new(ManagedPrefixList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ManagedPrefixList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedPrefixListEntry) DeepCopyInto(out *ManagedPrefixListEntry) {
	*out = *in
	if in.Cidr != nil {
		in, out := &in.Cidr, &out.Cidr
		*out = new(Cidr)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedPrefixListEntry.
func (in *ManagedPrefixListEntry) DeepCopy() *ManagedPrefixListEntry {
	if in == nil {
		return nil
	}
	out := new(ManagedPrefixListEntry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedPrefixListList) DeepCopyInto(out *ManagedPrefixListList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ManagedPrefixList, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedPrefixListList.
func (in *ManagedPrefixListList) DeepCopy() *ManagedPrefixListList {
	if in == nil {
		return nil
	}
	out := new(ManagedPrefixListList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ManagedPrefixListList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedPrefixListParameters) DeepCopyInto(out *ManagedPrefixListParameters) {
	*out = *in
	in.ManagedPrefixListSubParameters.DeepCopyInto(&out.ManagedPrefixListSubParameters)
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Region != nil {
		in, out := &in.Region, &out.Region
		*out = new(string)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedPrefixListParameters.
func (in *ManagedPrefixListParameters) DeepCopy() *ManagedPrefixListParameters {
	if in == nil {
		return nil
	}
	out := new(ManagedPrefixListParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedPrefixListSpec) DeepCopyInto(out *ManagedPrefixListSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ManagedPrefixListParameters.DeepCopyInto(&out.ManagedPrefixListParameters)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedPrefixListSpec.
func (in *ManagedPrefixListSpec) DeepCopy() *ManagedPrefixListSpec {
	if in == nil {
		return nil
	}
	out := new(ManagedPrefixListSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedPrefixListStatus) DeepCopyInto(out *ManagedPrefixListStatus) {
	*out = *in
	in.ConditionedStatus.DeepCopyInto(&out.ConditionedStatus)
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedPrefixListStatus.
func (in *ManagedPrefixListStatus) DeepCopy() *ManagedPrefixListStatus {
	if in == nil {
		return nil
	}
	out := new(ManagedPrefixListStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedPrefixListSubParameters) DeepCopyInto(out *ManagedPrefixListSubParameters) {
	*out = *in
	if in.AddressFamily != nil {
		in, out := &in.AddressFamily, &out.AddressFamily
		*out = new(string)
		**out = **in
	}
	if in.Entries != nil {
		in, out := &in.Entries, &out.Entries
		*out = make([]ManagedPrefixListEntry, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.MaxEntries != nil {
		in, out := &in.MaxEntries, &out.MaxEntries
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedPrefixListSubParameters.
func (in *ManagedPrefixListSubParameters) DeepCopy() *ManagedPrefixListSubParameters {
	if in == nil {
		return nil
	}
	out := new(ManagedPrefixListSubParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PeeredSubnetBuilder) DeepCopyInto(out *PeeredSubnetBuilder) {
	*out = *in
	if in.ClusterNames != nil {
		in, out := &in.ClusterNames, &out.ClusterNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PeeredSubnetBuilder.
func (in *PeeredSubnetBuilder) DeepCopy() *PeeredSubnetBuilder {
	if in == nil {
		return nil
	}
	out := new(PeeredSubnetBuilder)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PeeredSubnetSet) DeepCopyInto(out *PeeredSubnetSet) {
	*out = *in
	in.Public.DeepCopyInto(&out.Public)
	in.Private.DeepCopyInto(&out.Private)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PeeredSubnetSet.
func (in *PeeredSubnetSet) DeepCopy() *PeeredSubnetSet {
	if in == nil {
		return nil
	}
	out := new(PeeredSubnetSet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PeeredSubnets) DeepCopyInto(out *PeeredSubnets) {
	*out = *in
	if in.Cidrs != nil {
		in, out := &in.Cidrs, &out.Cidrs
		*out = make([]PeeredSubnetSet, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PeeredSubnets.
func (in *PeeredSubnets) DeepCopy() *PeeredSubnets {
	if in == nil {
		return nil
	}
	out := new(PeeredSubnets)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PeeredVpcLookup) DeepCopyInto(out *PeeredVpcLookup) {
	*out = *in
	if in.RemoteVpcs != nil {
		in, out := &in.RemoteVpcs, &out.RemoteVpcs
		*out = make([]VpcPeer, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PeeredVpcLookup.
func (in *PeeredVpcLookup) DeepCopy() *PeeredVpcLookup {
	if in == nil {
		return nil
	}
	out := new(PeeredVpcLookup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PeeredVpcNetwork) DeepCopyInto(out *PeeredVpcNetwork) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PeeredVpcNetwork.
func (in *PeeredVpcNetwork) DeepCopy() *PeeredVpcNetwork {
	if in == nil {
		return nil
	}
	out := new(PeeredVpcNetwork)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PeeredVpcNetwork) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PeeredVpcNetworkList) DeepCopyInto(out *PeeredVpcNetworkList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PeeredVpcNetwork, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PeeredVpcNetworkList.
func (in *PeeredVpcNetworkList) DeepCopy() *PeeredVpcNetworkList {
	if in == nil {
		return nil
	}
	out := new(PeeredVpcNetworkList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PeeredVpcNetworkList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PeeredVpcNetworkParameters) DeepCopyInto(out *PeeredVpcNetworkParameters) {
	*out = *in
	in.PeeredSubnets.DeepCopyInto(&out.PeeredSubnets)
	in.Tags.DeepCopyInto(&out.Tags)
	in.Peering.DeepCopyInto(&out.Peering)
	in.TransitGateway.DeepCopyInto(&out.TransitGateway)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PeeredVpcNetworkParameters.
func (in *PeeredVpcNetworkParameters) DeepCopy() *PeeredVpcNetworkParameters {
	if in == nil {
		return nil
	}
	out := new(PeeredVpcNetworkParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PeeredVpcNetworkSpec) DeepCopyInto(out *PeeredVpcNetworkSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	if in.AvailabilityZones != nil {
		in, out := &in.AvailabilityZones, &out.AvailabilityZones
		*out = make([]ShortAz, len(*in))
		copy(*out, *in)
	}
	in.PeeredVpcNetworkParameters.DeepCopyInto(&out.PeeredVpcNetworkParameters)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PeeredVpcNetworkSpec.
func (in *PeeredVpcNetworkSpec) DeepCopy() *PeeredVpcNetworkSpec {
	if in == nil {
		return nil
	}
	out := new(PeeredVpcNetworkSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PeeredVpcNetworkStatus) DeepCopyInto(out *PeeredVpcNetworkStatus) {
	*out = *in
	in.ConditionedStatus.DeepCopyInto(&out.ConditionedStatus)
	if in.CalculatedCidrs != nil {
		in, out := &in.CalculatedCidrs, &out.CalculatedCidrs
		*out = make(map[string][]string, len(*in))
		for key, val := range *in {
			var outVal []string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = make([]string, len(*in))
				copy(*out, *in)
			}
			(*out)[key] = outVal
		}
	}
	if in.SubnetBits != nil {
		in, out := &in.SubnetBits, &out.SubnetBits
		*out = make([]inputv1beta1.MultiPrefix, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.VpcLookup.DeepCopyInto(&out.VpcLookup)
	if in.Vpcs != nil {
		in, out := &in.Vpcs, &out.Vpcs
		*out = make(map[string]v1beta1.AwsVpc, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PeeredVpcNetworkStatus.
func (in *PeeredVpcNetworkStatus) DeepCopy() *PeeredVpcNetworkStatus {
	if in == nil {
		return nil
	}
	out := new(PeeredVpcNetworkStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PeeredVpcTags) DeepCopyInto(out *PeeredVpcTags) {
	*out = *in
	if in.Common != nil {
		in, out := &in.Common, &out.Common
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Subnet != nil {
		in, out := &in.Subnet, &out.Subnet
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Cluster != nil {
		in, out := &in.Cluster, &out.Cluster
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PeeredVpcTags.
func (in *PeeredVpcTags) DeepCopy() *PeeredVpcTags {
	if in == nil {
		return nil
	}
	out := new(PeeredVpcTags)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Peering) DeepCopyInto(out *Peering) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Peering.
func (in *Peering) DeepCopy() *Peering {
	if in == nil {
		return nil
	}
	out := new(Peering)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Peering) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PeeringList) DeepCopyInto(out *PeeringList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Peering, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PeeringList.
func (in *PeeringList) DeepCopy() *PeeringList {
	if in == nil {
		return nil
	}
	out := new(PeeringList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PeeringList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PeeringParameters) DeepCopyInto(out *PeeringParameters) {
	*out = *in
	in.LocalVpcDetails.DeepCopyInto(&out.LocalVpcDetails)
	in.PeerVpcDetails.DeepCopyInto(&out.PeerVpcDetails)
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PeeringParameters.
func (in *PeeringParameters) DeepCopy() *PeeringParameters {
	if in == nil {
		return nil
	}
	out := new(PeeringParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PeeringSpec) DeepCopyInto(out *PeeringSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.PeeringParameters.DeepCopyInto(&out.PeeringParameters)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PeeringSpec.
func (in *PeeringSpec) DeepCopy() *PeeringSpec {
	if in == nil {
		return nil
	}
	out := new(PeeringSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PeeringStatus) DeepCopyInto(out *PeeringStatus) {
	*out = *in
	in.ConditionedStatus.DeepCopyInto(&out.ConditionedStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PeeringStatus.
func (in *PeeringStatus) DeepCopy() *PeeringStatus {
	if in == nil {
		return nil
	}
	out := new(PeeringStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrefixList) DeepCopyInto(out *PrefixList) {
	*out = *in
	in.ManagedPrefixListSubParameters.DeepCopyInto(&out.ManagedPrefixListSubParameters)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrefixList.
func (in *PrefixList) DeepCopy() *PrefixList {
	if in == nil {
		return nil
	}
	out := new(PrefixList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RAM) DeepCopyInto(out *RAM) {
	*out = *in
	if in.Principals != nil {
		in, out := &in.Principals, &out.Principals
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RAM.
func (in *RAM) DeepCopy() *RAM {
	if in == nil {
		return nil
	}
	out := new(RAM)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubnetSet) DeepCopyInto(out *SubnetSet) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubnetSet.
func (in *SubnetSet) DeepCopy() *SubnetSet {
	if in == nil {
		return nil
	}
	out := new(SubnetSet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SubnetSet) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubnetSetList) DeepCopyInto(out *SubnetSetList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SubnetSet, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubnetSetList.
func (in *SubnetSetList) DeepCopy() *SubnetSetList {
	if in == nil {
		return nil
	}
	out := new(SubnetSetList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SubnetSetList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubnetSetParameters) DeepCopyInto(out *SubnetSetParameters) {
	*out = *in
	if in.Subnets != nil {
		in, out := &in.Subnets, &out.Subnets
		*out = make(map[ShortAz]*Cidr, len(*in))
		for key, val := range *in {
			var outVal *Cidr
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(Cidr)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	in.Tags.DeepCopyInto(&out.Tags)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubnetSetParameters.
func (in *SubnetSetParameters) DeepCopy() *SubnetSetParameters {
	if in == nil {
		return nil
	}
	out := new(SubnetSetParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubnetSetSpec) DeepCopyInto(out *SubnetSetSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.SubnetSetParameters.DeepCopyInto(&out.SubnetSetParameters)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubnetSetSpec.
func (in *SubnetSetSpec) DeepCopy() *SubnetSetSpec {
	if in == nil {
		return nil
	}
	out := new(SubnetSetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubnetSetStatus) DeepCopyInto(out *SubnetSetStatus) {
	*out = *in
	in.ConditionedStatus.DeepCopyInto(&out.ConditionedStatus)
	if in.Subnets != nil {
		in, out := &in.Subnets, &out.Subnets
		*out = make(map[AvailabilityZone]*SubnetId, len(*in))
		for key, val := range *in {
			var outVal *SubnetId
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(SubnetId)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.RouteTables != nil {
		in, out := &in.RouteTables, &out.RouteTables
		*out = make(map[AvailabilityZone]*RouteTableId, len(*in))
		for key, val := range *in {
			var outVal *RouteTableId
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(RouteTableId)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubnetSetStatus.
func (in *SubnetSetStatus) DeepCopy() *SubnetSetStatus {
	if in == nil {
		return nil
	}
	out := new(SubnetSetStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Subnets) DeepCopyInto(out *Subnets) {
	*out = *in
	if in.CidrBlocks != nil {
		in, out := &in.CidrBlocks, &out.CidrBlocks
		*out = make([]Cidr, len(*in))
		copy(*out, *in)
	}
	if in.Zones != nil {
		in, out := &in.Zones, &out.Zones
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Subnets.
func (in *Subnets) DeepCopy() *Subnets {
	if in == nil {
		return nil
	}
	out := new(Subnets)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TagSet) DeepCopyInto(out *TagSet) {
	*out = *in
	if in.All != nil {
		in, out := &in.All, &out.All
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Subnet != nil {
		in, out := &in.Subnet, &out.Subnet
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TagSet.
func (in *TagSet) DeepCopy() *TagSet {
	if in == nil {
		return nil
	}
	out := new(TagSet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TgwPeerWrapper) DeepCopyInto(out *TgwPeerWrapper) {
	*out = *in
	in.TransitGatewayPeer.DeepCopyInto(&out.TransitGatewayPeer)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TgwPeerWrapper.
func (in *TgwPeerWrapper) DeepCopy() *TgwPeerWrapper {
	if in == nil {
		return nil
	}
	out := new(TgwPeerWrapper)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TgwVpcDetailsWrapper) DeepCopyInto(out *TgwVpcDetailsWrapper) {
	*out = *in
	in.TransitGatewayVpc.DeepCopyInto(&out.TransitGatewayVpc)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TgwVpcDetailsWrapper.
func (in *TgwVpcDetailsWrapper) DeepCopy() *TgwVpcDetailsWrapper {
	if in == nil {
		return nil
	}
	out := new(TgwVpcDetailsWrapper)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TgwWrappedVpcWithProviderConfig) DeepCopyInto(out *TgwWrappedVpcWithProviderConfig) {
	*out = *in
	in.TransitGatewayVpcWithProviderConfig.DeepCopyInto(&out.TransitGatewayVpcWithProviderConfig)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TgwWrappedVpcWithProviderConfig.
func (in *TgwWrappedVpcWithProviderConfig) DeepCopy() *TgwWrappedVpcWithProviderConfig {
	if in == nil {
		return nil
	}
	out := new(TgwWrappedVpcWithProviderConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransitGateway) DeepCopyInto(out *TransitGateway) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransitGateway.
func (in *TransitGateway) DeepCopy() *TransitGateway {
	if in == nil {
		return nil
	}
	out := new(TransitGateway)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TransitGateway) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransitGatewayList) DeepCopyInto(out *TransitGatewayList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TransitGateway, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransitGatewayList.
func (in *TransitGatewayList) DeepCopy() *TransitGatewayList {
	if in == nil {
		return nil
	}
	out := new(TransitGatewayList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TransitGatewayList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransitGatewayNamedVpc) DeepCopyInto(out *TransitGatewayNamedVpc) {
	*out = *in
	in.TransitGatewayVpc.DeepCopyInto(&out.TransitGatewayVpc)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransitGatewayNamedVpc.
func (in *TransitGatewayNamedVpc) DeepCopy() *TransitGatewayNamedVpc {
	if in == nil {
		return nil
	}
	out := new(TransitGatewayNamedVpc)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransitGatewayParameters) DeepCopyInto(out *TransitGatewayParameters) {
	*out = *in
	in.RAM.DeepCopyInto(&out.RAM)
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransitGatewayParameters.
func (in *TransitGatewayParameters) DeepCopy() *TransitGatewayParameters {
	if in == nil {
		return nil
	}
	out := new(TransitGatewayParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransitGatewayPeer) DeepCopyInto(out *TransitGatewayPeer) {
	*out = *in
	if in.PrefixLists != nil {
		in, out := &in.PrefixLists, &out.PrefixLists
		*out = make([]PrefixList, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.ProviderConfigRef.DeepCopyInto(&out.ProviderConfigRef)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransitGatewayPeer.
func (in *TransitGatewayPeer) DeepCopy() *TransitGatewayPeer {
	if in == nil {
		return nil
	}
	out := new(TransitGatewayPeer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransitGatewaySpec) DeepCopyInto(out *TransitGatewaySpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.LocalVpc.DeepCopyInto(&out.LocalVpc)
	if in.RemoteVpcs != nil {
		in, out := &in.RemoteVpcs, &out.RemoteVpcs
		*out = make([]TransitGatewayVpcWithProviderConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Peers != nil {
		in, out := &in.Peers, &out.Peers
		*out = make([]TransitGatewayPeer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.TransitGatewayParameters.DeepCopyInto(&out.TransitGatewayParameters)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransitGatewaySpec.
func (in *TransitGatewaySpec) DeepCopy() *TransitGatewaySpec {
	if in == nil {
		return nil
	}
	out := new(TransitGatewaySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransitGatewayStatus) DeepCopyInto(out *TransitGatewayStatus) {
	*out = *in
	in.ConditionedStatus.DeepCopyInto(&out.ConditionedStatus)
	if in.LocalAttachmentIds != nil {
		in, out := &in.LocalAttachmentIds, &out.LocalAttachmentIds
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.RemoteAttachmentIds != nil {
		in, out := &in.RemoteAttachmentIds, &out.RemoteAttachmentIds
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransitGatewayStatus.
func (in *TransitGatewayStatus) DeepCopy() *TransitGatewayStatus {
	if in == nil {
		return nil
	}
	out := new(TransitGatewayStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransitGatewayVpc) DeepCopyInto(out *TransitGatewayVpc) {
	*out = *in
	if in.CidrBlocks != nil {
		in, out := &in.CidrBlocks, &out.CidrBlocks
		*out = make([]Cidr, len(*in))
		copy(*out, *in)
	}
	if in.PrefixLists != nil {
		in, out := &in.PrefixLists, &out.PrefixLists
		*out = make([]PrefixList, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.RouteTableIds != nil {
		in, out := &in.RouteTableIds, &out.RouteTableIds
		*out = make([]RouteTableId, len(*in))
		copy(*out, *in)
	}
	if in.SubnetIds != nil {
		in, out := &in.SubnetIds, &out.SubnetIds
		*out = make([]SubnetId, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransitGatewayVpc.
func (in *TransitGatewayVpc) DeepCopy() *TransitGatewayVpc {
	if in == nil {
		return nil
	}
	out := new(TransitGatewayVpc)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransitGatewayVpcWithProviderConfig) DeepCopyInto(out *TransitGatewayVpcWithProviderConfig) {
	*out = *in
	in.TransitGatewayNamedVpc.DeepCopyInto(&out.TransitGatewayNamedVpc)
	in.ProviderConfigRef.DeepCopyInto(&out.ProviderConfigRef)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransitGatewayVpcWithProviderConfig.
func (in *TransitGatewayVpcWithProviderConfig) DeepCopy() *TransitGatewayVpcWithProviderConfig {
	if in == nil {
		return nil
	}
	out := new(TransitGatewayVpcWithProviderConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransitGatewayWrapper) DeepCopyInto(out *TransitGatewayWrapper) {
	*out = *in
	in.TransitGatewayParameters.DeepCopyInto(&out.TransitGatewayParameters)
	in.TgwVpcDetailsWrapper.DeepCopyInto(&out.TgwVpcDetailsWrapper)
	if in.Peers != nil {
		in, out := &in.Peers, &out.Peers
		*out = make([]TgwPeerWrapper, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PrefixList != nil {
		in, out := &in.PrefixList, &out.PrefixList
		*out = make([]PrefixList, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.RemoteVpcs != nil {
		in, out := &in.RemoteVpcs, &out.RemoteVpcs
		*out = make([]TgwWrappedVpcWithProviderConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransitGatewayWrapper.
func (in *TransitGatewayWrapper) DeepCopy() *TransitGatewayWrapper {
	if in == nil {
		return nil
	}
	out := new(TransitGatewayWrapper)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VpcDetails) DeepCopyInto(out *VpcDetails) {
	*out = *in
	if in.CidrBlock != nil {
		in, out := &in.CidrBlock, &out.CidrBlock
		*out = make([]Cidr, len(*in))
		copy(*out, *in)
	}
	if in.ProviderConfigRef != nil {
		in, out := &in.ProviderConfigRef, &out.ProviderConfigRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.RouteTableIds != nil {
		in, out := &in.RouteTableIds, &out.RouteTableIds
		*out = make([]RouteTableId, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VpcDetails.
func (in *VpcDetails) DeepCopy() *VpcDetails {
	if in == nil {
		return nil
	}
	out := new(VpcDetails)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VpcNetwork) DeepCopyInto(out *VpcNetwork) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VpcNetwork.
func (in *VpcNetwork) DeepCopy() *VpcNetwork {
	if in == nil {
		return nil
	}
	out := new(VpcNetwork)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VpcNetwork) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VpcNetworkList) DeepCopyInto(out *VpcNetworkList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VpcNetwork, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VpcNetworkList.
func (in *VpcNetworkList) DeepCopy() *VpcNetworkList {
	if in == nil {
		return nil
	}
	out := new(VpcNetworkList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VpcNetworkList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VpcNetworkParameters) DeepCopyInto(out *VpcNetworkParameters) {
	*out = *in
	in.Tags.DeepCopyInto(&out.Tags)
	in.Subnets.DeepCopyInto(&out.Subnets)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VpcNetworkParameters.
func (in *VpcNetworkParameters) DeepCopy() *VpcNetworkParameters {
	if in == nil {
		return nil
	}
	out := new(VpcNetworkParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VpcNetworkSpec) DeepCopyInto(out *VpcNetworkSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.VpcNetworkParameters.DeepCopyInto(&out.VpcNetworkParameters)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VpcNetworkSpec.
func (in *VpcNetworkSpec) DeepCopy() *VpcNetworkSpec {
	if in == nil {
		return nil
	}
	out := new(VpcNetworkSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VpcNetworkStatus) DeepCopyInto(out *VpcNetworkStatus) {
	*out = *in
	in.ConditionedStatus.DeepCopyInto(&out.ConditionedStatus)
	in.AwsVpc.DeepCopyInto(&out.AwsVpc)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VpcNetworkStatus.
func (in *VpcNetworkStatus) DeepCopy() *VpcNetworkStatus {
	if in == nil {
		return nil
	}
	out := new(VpcNetworkStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VpcPeer) DeepCopyInto(out *VpcPeer) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VpcPeer.
func (in *VpcPeer) DeepCopy() *VpcPeer {
	if in == nil {
		return nil
	}
	out := new(VpcPeer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VpcPeering) DeepCopyInto(out *VpcPeering) {
	*out = *in
	if in.RemoteVpcs != nil {
		in, out := &in.RemoteVpcs, &out.RemoteVpcs
		*out = make([]WrappedVpcPeer, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VpcPeering.
func (in *VpcPeering) DeepCopy() *VpcPeering {
	if in == nil {
		return nil
	}
	out := new(VpcPeering)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VpcTags) DeepCopyInto(out *VpcTags) {
	*out = *in
	if in.Common != nil {
		in, out := &in.Common, &out.Common
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.PublicSubnetTags != nil {
		in, out := &in.PublicSubnetTags, &out.PublicSubnetTags
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.PrivateSubnetTags != nil {
		in, out := &in.PrivateSubnetTags, &out.PrivateSubnetTags
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VpcTags.
func (in *VpcTags) DeepCopy() *VpcTags {
	if in == nil {
		return nil
	}
	out := new(VpcTags)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WrappedVpcPeer) DeepCopyInto(out *WrappedVpcPeer) {
	*out = *in
	out.VpcPeer = in.VpcPeer
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WrappedVpcPeer.
func (in *WrappedVpcPeer) DeepCopy() *WrappedVpcPeer {
	if in == nil {
		return nil
	}
	out := new(WrappedVpcPeer)
	in.DeepCopyInto(out)
	return out
}
