---
apiVersion: v1
kind: Pod
metadata:
  name: mysql-client
  namespace: default
  labels:
    app: mysql-client
  annotations:
    cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
spec:
  securityContext:
    runAsNonRoot: true
    supplementalGroups: [10001]
    fsGroup: 10001
  containers:
    - name: mysql-client
      image: mysql:5.7
      imagePullPolicy: Always
      securityContext:
        runAsUser: 1000
        allowPrivilegeEscalation: false
        seccompProfile:
          type: RuntimeDefault
        capabilities:
          drop:
            - ALL
      stdin: true
      tty: true
      command: ["/bin/sh"]
