apiVersion: v1
data:
  registry_cicd_secret_ref: ${{ secrets.GITHUB_TOKEN }}
  registry_domain: ghcr.io
  registry_pull_secret_name: ghcr-pull-secret
  registry_username: build_bot
kind: ConfigMap
metadata:
  name: github-oci-registry-info
